### PR TITLE
boilerplate tests

### LINKED ISSUE #86: [DEV] boilerplate code: write tests
**Location**

`/`

____

**Description**

Tests should be written for the boilerplate code.

100% coverage for both back-end and front-end since it's the boilerplate code.

Unit and integration tests are needed. (UI/E2E tests can wait)

(Note: I did not make this part of #84 because otherwise the team will have to wait even longer before finally starting to code, this is the ONLY exception)

____

**Sources**

### PR DESCRIPTION
**Pull request by noahvsb**
**Issue(s)**

closes #86 

____

**Description**

Wrote tests for the boilerplate code. I have achieved 100% coverage on frontend and 98% on backend.

For the backend [this line](https://github.com/SELab-2/viernulvier-1/blob/bd5123830006f46b434da96569f3a3f9f54b0ce4/backend/src/server.ts#L71) was impossible to test.

An idea could be to put that line in a `main.ts` file and run that in the docker instead of `server.ts`; then we would exclude `main.ts` from the coverage report and we'd achieve 100% coverage for backend.

____

**Sources**

### CODE REVIEW

File: backend/src/server.ts [hunk 1]
```diff
@@ -1,40 +1,57 @@
-import Fastify from "fastify";
+import Fastify, { type FastifyInstance } from "fastify";
 import dbPlugin from "./db/postgres.js";
 import productionRoutes from "./routes/productions.js";
 
 import "dotenv/config";
 
-const isDebug = process.env["DEBUG"]?.toLowerCase() === "true";
-
-export const server = Fastify({
```
Comment (noahvsb) [inline backend/src/server.ts:9]: This export is useless and it makes the tests fail. If in the future the export is needed, then review your own code, because it shouldn't be necessary.

File: rundev.sh
Comment (noahvsb) [inline rundev.sh:1]: Just a `chmod +x rundev.sh`. I thought it might be nice to push this as well so we wouldn't need to chmod it each time we pull.

File: backend/test/server.test.ts [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+    });
+  });
+
+  describe("start()", () => {
+    beforeEach(() => {
+      vi.resetModules();
+    });
+
+    test("starts on default port 3000 when BACKEND_PORT is unset", async () => {
+      const { start } = await import("@/server.js");
```
Comment (Ikerstreamer) [inline backend/test/server.test.ts]: Why are we using a mix of both await import as well as ESM module based imports?

File: backend/test/server.test.ts [hunk 3]
```diff
@@ -0,0 +1,84 @@
+import { describe, test, expect, vi, beforeEach } from "vitest";
+
+vi.mock("@/db/postgres.js", () => ({
+  default: vi.fn(async (server: FastifyInstance) => {
+    server.pg = { query: vi.fn() } as any;
+  }),
+}));
+
+import { buildServer } from "@/server.js";
```
Comment (Ikerstreamer) [inline backend/test/server.test.ts]: Why aren't all module wide imports at the top of the file?

File: backend/src/server.ts (hunk 1 above)
Comment (Ikerstreamer) [reply backend/src/server.ts:9]: I mainly wrote it like this to start because the export existed before the buildServer method which is a way nicer apporach.

File: rundev.sh
Comment (Ikerstreamer) [reply rundev.sh:1]: This makes a lot of sense but I assumed I had already done this.

File: backend/src/server.ts
Comment (Simon-VdB) [inline backend/src/server.ts:1]: don't quite understand why that export caused problems, but I don't need to i think. It works the same way now, just not with that export. So I trust it.

File: frontend/test/components/HelloWorld.test.ts [hunk 4]
```diff
@@ -0,0 +1,25 @@
+import { mount } from "@vue/test-utils";
+import { describe, expect, test } from "vitest";
+import App from "@/App.vue";
+
```
Comment (Ikerstreamer) [inline frontend/test/components/HelloWorld.test.ts:4]: These tests aren't that useful as we will probs be removing this standard index page generated by vue for a real homepage.

**Review by Ikerstreamer — CHANGES_REQUESTED** [review]
Most of this looks pretty standard I did leave a few comments on some code quality stuff but for the most part it looks good.

**Review by Simon-VdB — DISMISSED** [review]
Ran the tests and coverage, and it works and is indeed 98 and 100

File: frontend/test/components/HelloWorld.test.ts (hunk 4 above)
Comment (noahvsb) [reply frontend/test/components/HelloWorld.test.ts:4]: True, but it can just serve as an example.

**Comment by lucasodb** [comment]
Backend test for port 3000 fails, not immediately clear why.

**Comment by noahvsb** [comment]
> Backend test for port 3000 fails, not immediately clear why.

I also don't understand, I recreated it by doing the following:

``` sh
pnpm run build-all
pnpm run coverage-all
```

But I was only able to recreate it once, every time after that the tests succeeded.

**Comment by noahvsb** [comment]
> > Backend test for port 3000 fails, not immediately clear why.
> 
> I also don't understand, I recreated it by doing the following:
> 
> ```shell
> pnpm run build-all
> pnpm run coverage-all
> ```
> 
> But I was only able to recreate it once, every time after that the tests succeeded.

Update: I found the error, fixing it is pretty hard though, since it's very sporadic.

File: backend/src/server.ts
Comment (noahvsb) [reply backend/src/server.ts:1]: The global server variable messed with the server variable in my tests. In hindsight I could've maybe just renamed it in my tests to fix it, but the global variable is not necessary and it's a bad practice to have global variables.

File: backend/test/server.test.ts (hunk 2 above)
Comment (noahvsb) [reply backend/test/server.test.ts]: Because of the `vi.resetModules()`, but I went for a different approach now that doesn't require the resetting of modules.

File: backend/test/server.test.ts (hunk 3 above)
Comment (noahvsb) [reply backend/test/server.test.ts]: I thought this was necessary for the mock, but it wasn't. Fixed now.

**Comment by noahvsb** [comment]
> Update: I found the error, fixing it is pretty hard though, since it's very sporadic

Update 2: fixed it

**Review by lucasodb — APPROVED** [review]
All tests now pass, with expected coverage.

**Review by Ikerstreamer — APPROVED** [review]
The tests do work and code quality looks up[ to par I suggest we merge this and then direct after it we merge #150. Or even just #150 as I did try and keep the branch up to date such that there would be 0 merge conflicts.
